### ISSUE TITLE
broken link to the blog post

### ISSUE THREAD

**Issue by brunocrt** [jpkrohling/opentelemetry-collector-deployment-patterns#2]
Hi Juraci,

Thanks for sharing this content!
I noticed there is a broken link to your blog on the following post 
https://github.com/jpkrohling/opentelemetry-collector-deployment-patterns/tree/main/pattern-3-kubernetes
It has a typo (":" char at the end of the URL).

PS: I'm also from MT
PS2: I'm using grafana tempo with java otel agent

**Comment by jpkrohling** [comment]
Obrigado, Xomano!
